# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20dc674b2806b78f2b9ecb55f4dcd081d87a9fd6dbfac47eb2ab82f2eb3557b07b98b92f9c05ed0dcdfa8cd556180402706da5dd3cce1e89be75d86207bd51e4

test:
  secret_key_base: 34755e363a757e97df3fad2c4938158c3dd81c6d6d25cdd18b1ced1e5fbefe9819143a3afc912082613ba4db1a298bf3f7c6bc667afc5ea9c0773305954ed698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
